/**
 * RSS Source category types
 */
export enum SourceCategoryEnum {
  COMPANY_NEWS = 'COMPANY_NEWS',
  ECONOMY = 'ECONOMY',
  SECTOR_NEWS = 'SECTOR_NEWS',
  INTERNATIONAL = 'INTERNATIONAL',
  POLICY = 'POLICY',
  FINANCIAL_MARKETS = 'FINANCIAL_MARKETS',
}

