/**
 * News main category
 */
export enum NewsCategoryEnum {
  COMPANY_NEWS = 'COMPANY_NEWS',
  MACRO_ECONOMY = 'MACRO_ECONOMY',
  SECTOR_NEWS = 'SECTOR_NEWS',
  INTERNATIONAL = 'INTERNATIONAL',
  POLICY_REGULATION = 'POLICY_REGULATION',
  FINANCIAL_MARKETS = 'FINANCIAL_MARKETS',
}

